# Generated by Django 5.0.3 on 2024-05-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_koment_tov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koment',
            old_name='tov',
            new_name='kom',
        ),
    ]
