# Generated by Django 5.0.3 on 2024-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tovar_img_tovar_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании', 'verbose_name_plural': 'Компания'},
        ),
        migrations.AlterModelOptions(
            name='kategor',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='pod_kat',
            options={'verbose_name': 'Под категории', 'verbose_name_plural': 'Под категории'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профиль'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристика'},
        ),
        migrations.AlterModelOptions(
            name='tovar',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
