# Generated by Django 5.0.3 on 2024-05-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_koment_name_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koment',
            name='name',
        ),
    ]
