# Generated by Django 5.0.3 on 2024-05-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_koment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koment',
            name='user',
        ),
    ]
