# Generated by Django 5.0.3 on 2024-05-17 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_koment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koment',
            options={},
        ),
        migrations.RemoveField(
            model_name='koment',
            name='koment',
        ),
        migrations.RemoveField(
            model_name='koment',
            name='star',
        ),
        migrations.AddField(
            model_name='koment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='koment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
