# Generated by Django 5.0.3 on 2024-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_koment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='koment',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='koment',
            name='rating',
            field=models.TextField(null=True),
        ),
    ]
