# Generated by Django 5.0.3 on 2024-05-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_koment_content_alter_koment_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koment',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='koment',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='koment',
            name='rating',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='koment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
