# Generated by Django 5.0.3 on 2024-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_koment_name_profile_name_alter_koment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='koment',
            name='rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
