# Generated by Django 5.0.3 on 2024-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_koment_content_alter_koment_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profil/default.jpg', upload_to='profil'),
        ),
    ]
